### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by MartinCapraro** [rparini/cxroots#383]
The link to the ZEAL package in the readme ([http://cpc.cs.qub.ac.uk/summaries/ADKW](http://cpc.cs.qub.ac.uk/summaries/ADKW)) is currently returning a 404. Some quick googling did not help, and it looks like the internet archive last had a successful archive in 2007.

**Comment by rparini** [comment]
Thanks for spotting this! I've found https://elsevier.digitalcommonsdata.com/datasets/yc9vv7rwyj/1 which still seems to work so I will change the link to that
